### ISSUE TITLE
Wofür ist die Klasse Timer und deren Instanz noch gut?

### ISSUE THREAD

**Issue by armin-reichert** [Rihpsalis/GhostGame#14]
Du verwendest doch `AnimationTimer` als game clock...

**Comment by Rihpsalis** [comment]
Die Klasse Timer ist für die Geschwindigkeit der refresh rate der Animation vom Spieler zuständig. Im weiteren Verlauf dann auch für andere Objekte die eine animierte Textur haben

**Comment by armin-reichert** [comment]
Darauf bin ich mal gespannt :-)
