### ISSUE TITLE
Darf der Verwender Deines Spiels den Fullscreen-Modus nicht verlassen?

### ISSUE THREAD

**Issue by armin-reichert** [Rihpsalis/GhostGame#15]
`stage.setFullScreenExitKeyCombination(KeyCombination.NO_MATCH);`

Würde nicht wollen, wenn ein Programm sich mir im Fullscreen-Modus öffnet und ich diesen nur schwer wieder verlassen könnte.

**Comment by Rihpsalis** [comment]
Bis jetzt soll es schon so sein. Im weiteren wenn das Spiel irgenwann gestalt annimmt werde ich auch das verlassen des Fullscreens zulassen.

**Comment by armin-reichert** [comment]
Ich kann davon nur abraten, dem Benutzer eines Programms einen Fullscreen-Modus vorschreiben zu wollen. Das findet der u.U. gar nicht nett und kommt nie wieder ;-)
