### ISSUE TITLE
Die Klasse Panel ist mehr oder weniger überflüssig

### ISSUE THREAD

**Issue by armin-reichert** [Rihpsalis/GhostGame#16]
Da `Panel` von `Canvas` ableitet, hast Du den `GraphicsContext` des Canvas (1:1 Relation zwischen Canvas und GraphicsContext) per `getGraphicsContext2D()` (und umgekehrt den Canvas per `g.getCanvas()` immer griffbereit. Also benötigts Du die beiden Referenzen für Foreground/Backgriund sowieso nicht. Was bleibt dann von dieser Klasse noch übrig?

**Comment by Rihpsalis** [comment]
#7

**Comment by Rihpsalis** [comment]
In Panel füge ich die Gridmap und Player dem GraphicsContext zu
