### ISSUE TITLE
Klasse ResourceLoader

### ISSUE THREAD

**Issue by armin-reichert** [Rihpsalis/GhostGame#17]
Bitte den Code und die Kommentare genau lesen:
```
/* The path under your src/main/resources folder where you store your images... */
private static final String ROOT = "src/main/resources";
```

Da steht doch *under*! Also wenn Du z.B. deine Grafiken unterhalb von `src/main/resources/graphics/` ablegst, dann sollte hier
```
private static final String ROOT = "graphics/";
```

stehen. So war es gedacht.

**Comment by Rihpsalis** [comment]
Da gibt es bei mir terrain und player. Ich belasse es dann einfach bei "/"

**Comment by armin-reichert** [comment]
Genau. Und dann schreibst Du zum Laden einfach `getClass().getResource("player/name_des_bilds.png")` oder `ResourceManager.image("player/name_des_bilds.png")`.

**Comment by Rihpsalis** [comment]
ja hab ich schon geändert. Danke

**Comment by Rihpsalis** [comment]
Nachdem ich den code zu:
`movingImagesL[i] = new Image(ResourceLoader.image("player/MovingLeft_" + i + ".png").toString(), playerSize, playerSize, false, false);`
geändert habe kriege ich immernoch eine Fehlermeldung:
`Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.util.MissingResourceException: Missing resource, path=/player/MovingRight_0.png
	at main.java.ResourceLoader.url(ResourceLoader.java:37)
	at main.java.ResourceLoader.urlFromRelPath(ResourceLoader.java:26)
	at main.java.ResourceLoader.image(ResourceLoader.java:47)
	at main.java.Player.<init>(Player.java:37)
	at main.java.App.start(App.java:47)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	... 1 more`

**Comment by armin-reichert** [comment]
Ich sehe gerade: Wenn Du den "ResourceLoader" zum Laden von Bildern verwenden möchtest, die Du gleich auch mit diversen Parametern skalieren willst, muss Du dem ResourceLoader natürlich eine entsprechende neue Methode mit diesen Parametern hinzufügen.

**Comment by armin-reichert** [comment]
```movingImagesL[i] = new Image(ResourceLoader.image("player/MovingLeft_" + i + ".png").toString(), playerSize, playerSize, false, false);```

Das ist ja auch so nicht korrekt. Wie oben beschrieben, musst Du dem ResourceLoader  entweder eine neue `image(...)` Methode spendieren, die die zusätzlichen Parameter enthält, oder Du erzeugst nur den URL mit ResourceLoader (spart ein wenig Schreibarbeit) und gibst das Ergebnis an `new Image(url, ...)` weiter, etwa:

```
var url = ResourceLoader.urlFromRelPath("player/MovingLeft_"+i+".png");
movingImagesL[i] = new Image(url, ...)
```

**Comment by Rihpsalis** [comment]
gut war gerade eigentlich dabei die neue Methode zu schreiben aber ich denke man kann es mit dem 2. Vorschlag simpler gestalten. Danke sehr :)

**Comment by armin-reichert** [comment]
Die zusätzliche Methode hätte aber den Vorteil, dass man kürzeren Aufrufcode bekommt, also

```var image = ResourceLoader.image("player/image_name.png", width, height, preserveRatio, smooth);```

anstelle von

```
var image = new Image(
  ResourceLoader.urlFromRelPath("player/image_name.png").toString(), 
  width, height, preserveRatio, smooth);
```

**Comment by Rihpsalis** [comment]
Dass ist der Fehler den ich gerade bekomme:
![image](https://github.com/Rihpsalis/GhostGame/assets/130935178/46c01994-5d1b-4166-820f-f416863ba0a2)
soll ich adapten?

**Comment by armin-reichert** [comment]
Da fehlt noch `toString()` bzw. `toExternalForm()`. Es wird also noch länger :-) Vielleicht doch eine neue Methode spendieren?

**Comment by armin-reichert** [comment]
Und bitte geschweifte Klammern um den Rumpf der for-Schleife, siehe https://github.com/Rihpsalis/GhostGame/issues/19

**Comment by Rihpsalis** [comment]
Der Fehler Code ist nach wie vor

Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.util.MissingResourceException: Missing resource, path=/player/MovingRight_0.png
	at main.java.ResourceLoader.url(ResourceLoader.java:37)
	at main.java.ResourceLoader.urlFromRelPath(ResourceLoader.java:26)
	at main.java.Player.<init>(Player.java:39)
	at main.java.App.start(App.java:47)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	... 1 more

Process finished with exit code 1

**Comment by armin-reichert** [comment]
Zeig mal den Code. Oder mach einfach mal einen Push und wir korrigieren es dann.

**Comment by Rihpsalis** [comment]
ist gepushed

**Comment by armin-reichert** [comment]
Und die Bilder?

**Comment by Rihpsalis** [comment]
die bilder pushe ich nichtmehr. die sind im gitignore file
![image](https://github.com/Rihpsalis/GhostGame/assets/130935178/735eb3a1-c98f-41ab-bd9b-38a4b06d622a)

**Comment by armin-reichert** [comment]
Wieso denn das? Wie soll denn jemand das Projekt bauen und laufen lassen ohne die Bilder?

**Comment by Rihpsalis** [comment]
Hmm ja ist ein Punkt aber ich hatte eher bedenkten falls sich jemand meine Bilder einfach nimmt

**Comment by armin-reichert** [comment]
Na so funktioniert das hier mit Open Source und Zusammenarbeit aber nicht. Leg doch ein Lizenzfile in dein Repository, dort kannst Du dann festlegen, wer Deine Sachen wie verwenden darf.

**Comment by Rihpsalis** [comment]
hab alle Texturen hochgeladen.

**Comment by armin-reichert** [comment]
Sehr schön. 

Habe Dein Repository "gecloned" und in meine IDE (Eclipse) importiert. Jetzt weiß Eclipse natürlich nicht, wie es dieses Projekt bauen soll. Daher habe ich eine Maven Projektdatei (`pom.xml`) angelegt. 

Als erstes fällt dann auf, dass  `package main.java` nicht korrekt ist. Die Paketstruktur fällt nach Maven-Konventionen ja erst unterhalb des Sourceverzeichnis (`src/main/java`) an. Daher liegen alle Deine Klassen im leeren "Defaultpaket", d.h. man muss alle package Deklarationen entfernen. (Später solltest Du dann über eine passende Packagestruktur nachdenken und entsprechende package x.y.z Deklarationen wieder einfügen).

Wenn ich das Programm dann mit Maven baue und starte, kommt eine Exception, weil Du in `GridMap`versuchst, die Textdatei über einen Filestream zu laden. Das funktioniert aber mit einer URL so nicht. Stattdessen folgendes tun (Ab Zeile 76):
```
try {
  reader = new InputStreamReader(ResourceLoader.urlFromRelPath(
   "terrain/gridmap/" + gridmapInUse + "_values.txt").openStream());
} catch (Exception e) {
  throw new RuntimeException(e);
}
```
Dazu die Variable `fileReader` ersetzen durch `InputStreamReader reader;`.

Dann startet das Programm und - knallt mir einen Fullscreen-Mode vor den Latz, aus dem ich weder mit Escape noch  F11 wieder herauskomme. Ich habe das bereits erwähnt, sowas ist nicht benutzerfreundlich. Also bitte entweder den Hinweis, wie man den Fullscreen-Mode wieder beendet, wieder einblenden, oder (besser) erst gar nicht im Fullscreen-Mode starten.

Soll ich Dir die Maven `pom.xml` irgendwie zukommen lassen?

Gruß Armin

**Comment by Rihpsalis** [comment]
hallo, nacheiner kleinen Pause bin ich wieder zurück und das problem

> Der Fehler Code ist nach wie vor
> 
> Exception in Application start method Exception in thread "main" java.lang.RuntimeException: Exception in Application start method at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901) at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196) at java.base/java.lang.Thread.run(Thread.java:1589) Caused by: java.util.MissingResourceException: Missing resource, path=/player/MovingRight_0.png at main.java.ResourceLoader.url(ResourceLoader.java:37) at main.java.ResourceLoader.urlFromRelPath(ResourceLoader.java:26) at main.java.Player.(Player.java:39) at main.java.App.start(App.java:47) at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847) at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484) at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457) at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456) at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184) ... 1 more
> 
> Process finished with exit code 1

besteht immernoch. Trotzdem vielen Dank für die ganze Hilfe, ich denke ich benötige die pom.xml nicht und ich wede mich sobald dieses Problem gelöst ist direkt an die Benutzerfreundlickeit setzen. :)

**Comment by armin-reichert** [comment]
Ich würde Dir anbieten, die auftretenden Probleme eins nach dem anderen zu beheben. Ob Du dein Projekt mit Maven oder Gradle oder sonstwie verwaltest, ist natürlich Deine Entscheidung. Allerdings hilft es netten Menschen, die Dir helfen wollen, wenn sie einen definierten Weg haben, Dein Projekt auf ihrem Computer zu bauen, ohne z.B. die selbe IDE wie Du zu verwenden (IntelliJ IDEA nehme ich an).

Vielleicht möchte der Code Dir auch sagen, dass es jetzt an der Zeit ist, den Umgang mit dem Debugger zu lernen 😁 Also mal im Debugger vor der Stelle, wo die Exception ausgelöst wird, einen Breakpoint setzen und sich die Inhalte der Variablen genau anschauen.

**Comment by armin-reichert** [comment]
Hab's gerade mal bei mir getestet. Ich bekomme keine Exception und die Bilder für die Geistanimation werden korrekt geladen. Wenn Du möchtest, kannst Du mich ja in Deinem Repository als "collaborator" eintragen, dann würde ich das Projekt mit meinen Korrekturen und dem pom.xml aktualisieren und Du kannst dann auf diesem Stand aufsetzen.

**Comment by Rihpsalis** [comment]
habe ich gemacht sollte funktionieren

**Comment by armin-reichert** [comment]
Soll ich mal mein Version "pushen"? Dein IntelliJ wird das pom.xml erkennen und Dich fragen, ob das Maven Projekt geladen werden soll (oder so ähnlich). Das einfach bestätigen.

**Comment by Rihpsalis** [comment]
ok

**Comment by armin-reichert** [comment]
Dann mach mal ein Update/Pull.

**Comment by Rihpsalis** [comment]
aber ich verstehe nicht warum die exakt gleiche Code Zeile in dem neuen Code funktioniert im alten allerdings nicht

**Comment by armin-reichert** [comment]
Es kommt ja auch darauf an, wo die Ressourcen nach dem Kompilieren landen (Classpath). Bei dem aktuellen Projektlayout (nach Mavenkonvention) ist alles, wo es hingehört.

Wenn Du auf der Kommandozeile den Befehl `mvn clean install` eingibst (Voraussetzung: Maven installiert), dann wird auch ein ausführbares jar-File ("shaded jar") gebaut, es landet im `target` Verzeichnis.
