### ISSUE TITLE
Bitte die Bilder etc. unter src/main/resources ablegen

### ISSUE THREAD

**Issue by armin-reichert** [Rihpsalis/GhostGame#18]

**Comment by Rihpsalis** [comment]
sind alle außer die Bilder die ich zum testen benutze

**Comment by armin-reichert** [comment]
"Testen" bezieht sich hier aber auf speziellen Testcode, wie z,B. "unit tests". Die zur Anwendung gehörenden Ressourcen bitte nach `src/main/resources` verschieben.

**Comment by Rihpsalis** [comment]
Erledigt

**Comment by armin-reichert** [comment]
Und wo sind sie? :-)

**Comment by Rihpsalis** [comment]
das nächste Problem ist mir zwischen den Commit/push gekommen

**Comment by armin-reichert** [comment]
Wie gesagt, immer schön eins nach dem anderen erledigen :-)
