### ISSUE TITLE
Stilempfehlung

### ISSUE THREAD

**Issue by armin-reichert** [Rihpsalis/GhostGame#19]
Den Rumpf einer if, while, ... Anweisung  *immer* als Block, also innerhalb geschweifter Klammern schreiben, auch wenn es nur eine einzelne Anweisung ist. (Ausnahme vielleicht bei einer "return"-Anwesiung)

**Comment by Rihpsalis** [comment]
wenn es nur eine for bzw. if schleife ist habe ich lieber keine Klammern drum stehen. Ich meine wenns ein feature ist? :)

**Comment by armin-reichert** [comment]
Glaub mir, es gibt in diesem Metier Dinge, die man einfach tut :-) Und das aus guten Gründen.
