### ISSUE TITLE
Statt src/main/resources in .gitignore Lizenzdatei anlegen oder Projekt auf privat stellen

### ISSUE THREAD

**Issue by armin-reichert** [Rihpsalis/GhostGame#21]

**Comment by Rihpsalis** [comment]
welche license würde bei mir am besten zutreffen, weil z.B. mit der MIT License darf jeder meinen Code usw. weiter / Kommerziell verwenden. Vorschläge?

Es wär für mich wichtig dass man den Code zwar verwenden darf um sich eine Kopie von meinem Programm zu erstellen, aber das niemand dieses kommerziell nutzen darf. Weiterverwendung wäre für mich nach Nennung von mir ok.

**Comment by armin-reichert** [comment]
Wenn Du ein Repository anlegst, werden Dir alle möglichen Lizenzen vorgeschlagen, such Dir einfach eine aus. Aber was ist an einem Anfängerprojekt so besonders, dass man es durch eine Lizenz schützen müsste? Ich würd da mal ein bisschen locker bleiben.
