### ISSUE TITLE
GameTimer class looks dubious to me

### ISSUE THREAD

**Issue by armin-reichert** [Rihpsalis/GhostGame#5]
I cannot quite understand your GameTimer class with its own thread. In JavaFX (in contrast to e.g. Swing) there is no need for a separate thread for the "game loop" / simulation. Everything is running on the "JavaFX Application Thread". JavaFX provides an AnimationTimer and a Timeline class where you can call into your game loop and render code. Note that the AnimationTimer runs with the refresh rate of the screen device so you cannot expect that it always run with e.g. 60 Hz.

**Comment by Rihpsalis** [comment]
so should i change GameTimer to extend from AnimationTimer or write the whole code into AnimationTimer?

**Comment by armin-reichert** [comment]
See https://edencoding.com/javafxanimation-transitions-timelines-and-animation-timers/#animation-timer

Create a subclass of AnimationTimer (maybe an anon subclass) and override the handle() method. This method is called FPS times a second and there you can attach your game update/render stuff.

Do NOT create your own game thread as you would for example in a Swing based game.

**Comment by Rihpsalis** [comment]
done, thank you very much :)
