### ISSUE TITLE
Why two different graphics context references for the same canvas?

### ISSUE THREAD

**Issue by armin-reichert** [Rihpsalis/GhostGame#7]
I don't get why there are two different GraphicsContext references for the same canvas. In JavFX the graphics context is in a 1:1 association with its canvas.

**Comment by Rihpsalis** [comment]
i saw online that there can be 2 grapics context for one canvas so to mak it more clear i made a Foreground GrapicsContext (gcFg) and a Background GrapicsContext gcBg

**Comment by armin-reichert** [comment]
And what is this good for?

**Comment by Rihpsalis** [comment]
So that i can render the player infront of the Background

**Comment by armin-reichert** [comment]
And why not render the background and **then** the player using the same graphics?

**Comment by Rihpsalis** [comment]
to mak it clearer and easier to understand once I progress with my project

**Comment by armin-reichert** [comment]
Was soll der Sinn davon sein, dem selben Grafikkontext zwei Namen/Referenzen zu geben, wenn es doch nur auf die Reihenfolge ankommt, in der er aufgerufen wird?

**Comment by Rihpsalis** [comment]
wenn ich diese zwei GrapicsContext habe muss ich im späteren nich auf die reihenfolge meines renderings achten da die reihenfolge durch die zwei Referenzen geregelt ist

**Comment by armin-reichert** [comment]
Das ergibt doch keinen Sinn. Du musst in jedem Fall die `render()` Aufrufe in der richtigen Reihenfolge machen, auch wenn der `GraphicsContext` immer z.B. einfach `g` heißt und das die einzige Referenz ist.

**Comment by Rihpsalis** [comment]
#Ich finde es ergibt Sinn, aber ich bin ja auch noch nicht so erfahren was programmieren angeht. Dann hör ich lieber mal auf jemand der weiß wies gemacht wird. Danke für die Geduld

**Comment by armin-reichert** [comment]
Wie lange programmierst Du denn schon? Bist Du Student, Schüler...?

**Comment by Rihpsalis** [comment]
Schüler. Ich programmiere seit etwa 3 Monaten

**Comment by armin-reichert** [comment]
Super. Dann hast Du ja noch einiges vor Dir.

Ich empfehle, nicht zu viele verschiedene Dinge auf einmal zu machen. Und eines musst Du wissen, man lernt jeden Tag was dazu. Auch ich, der vor mehr als 40 Jahren sein erstes Programm geschrieben hat.
