### ISSUE TITLE
Ressourcen gehören unter src/main/resources

### ISSUE THREAD

**Issue by armin-reichert** [Rihpsalis/GhostGame#9]
Wenn man sich an die Maven-Konventionen hält, gehören die Ressourcen nach `src/main/resources`. Das entsprechende Verzeichnis ` src/test/resources` ist für Testcode-Ressourcen vorgesehen. An der Art, wie die Ressourcen geladen werden, sollte sich nichts ändern. Vergleiche die Diskussion, dass man Ressourcen nicht als Files über einen Verzeichnispfad, sondern per Classloader aus dem "classpath" oder "module path" laden sollte.

**Comment by Rihpsalis** [comment]
ok danke werd ich machen.
